.gitignore
example/main.go
graphql/introspection/introspection.go
graphql/introspection/introspection.graphql
graphql/introspection/introspection_test.go
graphql/introspection/test-schema.json

One can generate a schema JSON object that can be used for generating
type information for a GraphQL client
(e.g. https://github.com/apollographql/apollo-codegen).

introspection: Add function to execute introspection query

---

graphql/parser.go
graphql/parser_test.go

Arrays were supported in JSON, but not if specified manually in the
query. Fix that.

graphql: support arrays in parser

---

graphql/introspection/test-schema.json
graphql/schemabuilder/reflect.go

Pointers are nullable, non pointer types are not.
With this commit input and output types still have slightly different
nullability rules (around slices and slice elements), but this commit
brings them closer together.

graphql: support NonNull in input types

---

batch/batch.go
batch/batch_test.go

Batching is useful to reduce the number of RPCs issued by
queries such as
{
events {
venue {
address
}
}
}
Naively, the venue resolver might issue an RPC for every single event.
Using batching, a batching venue resolver instead might issue a single
RPC for all events at once.
Batching is inspired by libraries like Facebook's dataloader, but
because Go has no promises, it instead uses time-based batching.
Experimentally, the extra latency can be as little as 200 microseconds
per call with reasonable results.
I attempted a different approach using explicit tracking of running
goroutines, but that felt brittle: Every goroutine would have to
carefully announce to the world when it is running and when not, and
that seems too easy to accidentally mess up, and hard to debug when
that happens. …

batch: add a batching package (without tracking goroutines)

---

graphql/await.go
graphql/await_test.go
graphql/executor.go
graphql/executor_test.go
graphql/schemabuilder/reflect_test.go
graphql/server.go
reactive/diff/diff.go
reactive/diff/diff_test.go

This commit removes the diff.Object and diff.List intermediate objects
and computes diffs over standard JSON objects instead. This simplifies
the API and all callsites, since they no longer have to wrangle these
special types.

reactive/diff: use standard JSON objects, add documentation

---

graphql/end_to_end_test.go
graphql/executor_test.go
graphql/introspection/introspection.go
graphql/parser.go
graphql/parser_test.go
graphql/schemabuilder/perf_test.go
graphql/schemabuilder/reflect_test.go
graphql/server.go

Query names are helpful in monitoring, so keep track of them after
parsing and during execution.

graphql: track query name and report name in tags

---

graphql/end_to_end_test.go
graphql/executor.go
graphql/executor_test.go
graphql/introspection/introspection.go
graphql/schemabuilder/perf_test.go
graphql/schemabuilder/reflect_test.go
graphql/server.go

When eg.
```
query testQuery {
user {
name
}
}
```
fails to resolve user.name with error "RPC failed", the error now
prints as "testQuery.user.name: RPC failed". The addition of
"testQuery." is new.
To make this work, start passing around a query object instead of the
raw selection set.

graphql: include query name in error

---

graphql/schemabuilder/reflect.go
graphql/schemabuilder/reflect_test.go

Fixes a bug where alias types would fail with 
```bash
panic: reflect.Set: value of type *int64 is not assignable to type *schemabuilder.alias
```
(See first commit)

Support optional (pointer) alias types

---

graphql/schemabuilder/reflect.go
graphql/schemabuilder/reflect_test.go

```js
> JSON.stringify(new Date())
"2017-05-09T21:05:58.318Z"
> JSON.stringify({ s: new Date() })
{"s":"2017-05-09T21:06:03.006Z"}
```
It's nice the js will also stringify `Date` objects as ISO8601 as well.

Support ISO8601 timestamps for time.Time

---

graphql/middleware.go
graphql/server.go
opentracingkit/opentracingkit.go

This PR adds support for middleware in computing queries/mutations.
An example use case for this might be contributing an id to all computations:
```golang
c.Use(func(input *graphql.ComputationInput, output *graphql.ComputationOutput, next graphql.NextFunc) {
output.Metadata["computationId"] = uuid.New()
next(input, output);
})
```
the `Metadata` map is appended to the websocket response alongside the `message`:
Another use-case might be contributing to the `context`:
```golang
c.Use(func(input *graphql.ComputationInput, output *graphql.ComputationOutput, next graphql.NextFunc) {
input.Ctx = opentracing.StartSpanFromContext(input.Ctx, "graphql.query");
next(input, output);
})
```
- note that this PR also removes starting a subscription span from the graphql handler.
- if this is a pattern …

Computation Middleware

---

batch/batch.go

Bumping up the default wait interval from 200us to 1ms, to better
accumulate function invocations into batch requests.

thunder batch: Increase DefaultWaitInterval to 1ms

---

graphql/introspection/introspection_test.go
graphql/introspection/test-schema.json
graphql/schemabuilder/reflect.go

r? @jellevandenhooff 
For context, we cache the type of the known structs that we have already seen so that we do not need to do reflection checks on structs multiple times. However, this cache check prevents the rest of the function from correctly wrapping non-nullable fields in `graphql.NonNull{}`.
In practice, this bug is visible when a resolver returns a non-pointer struct type of a struct type that the schemabuilder has already seen.
In this commit, I've removed the cache check. Note that the buildStruct function still has this same cache check repeated the beginning of its body, so we are still avoiding the penalty of re-reflecting on seen structs, but we are allowing getType to run its null vs. non-null logic.
The first commit adds a failing test case and the second adds the fix.

Fix incorrect type inference for non-null fields

---

graphql/introspection/introspection_test.go
graphql/introspection/test-schema.json
graphql/schemabuilder/reflect.go
graphql/schemabuilder/reflect_test.go
graphql/schemabuilder/types.go

This PR allows resolvers to be marked non-nullable. By default, pointer types will continue to be nullable, but can be marked otherwise.
```golang
object.FieldFunc("optional", function(ctx context.Context) (*User, object) {
// ...
})
object.FieldFunc("required", function(ctx context.Context) (*User, object) {
// ...
}, schemabuilder.NonNullable)
```

Non-nullable resolver functions

---

graphql/schemabuilder/reflect.go
graphql/schemabuilder/reflect_test.go

This PR fixes an issue with #49 where the non-null result checking overrides the existence of an error passed back from the field func.

Fix resolver errors failing to pass through to executor

---

graphql/introspection/test-schema.json
graphql/schemabuilder/reflect.go

In the case where the same struct is used as both a field and an input argument, AND it was suffixed with `Input`, we would re-use the output types as an input type in the graphql schema. This would cause some tools using the schema output to fail to use the separate introspected types.

graphql: fix issue where suffixed with Input would fail

---

graphql/executor.go
graphql/executor_test.go
graphql/types.go
livesql/binlog.go

Fixes a bug when the same fragment is used multiple times
in a query and the args of its selections are parsed
multiple times, causing query preparation errors
(I observed [this one](https://github.com/samsarahq/thunder/blob/master/graphql/schemabuilder/reflect.go#L304) specifically).
Tested manually. Also ran all unit tests locally and they passed.

Parse Selection Args Only Once

---

diff/diff_test.go
graphql/executor.go
graphql/executor_test.go

Updates the executor to unwrap pointers to scalar values to their raw values if the pointer is non-nil. This fixes an issue where pointers were being compared when calculating update diffs instead of underlying values leading to unnecessary updates.
Executor and diff tests were updated to verify the correct behavior.

Ryanr/scalar: Unwrap pointers to scalar values

---

livesql/binlog.go

This reverts commit a4f4690203e2f2c3e1e6d26d368ec3a02a8dd4b3.
We are worried that this is too much of a breaking change. Instead, consider vendoring to our older version of the go-mysql package.
This PR will break travis, which we should fix separately.

Revert "livesql/binlog: update function params"

---

graphql/executor.go
graphql/parser.go
graphql/server.go

This PR distinguishes parsing errors (client input errors) from safe errors used otherwise.

Distinguish ClientError from SafeError

---

graphql/server.go
reactive/rerunner.go
reactive/rerunner_test.go

This PR changes the rerunner to accept a sentinel for retrying the computation without dumping the previously cached results. For graphql subscriptions, it sends this sentinel value for recomputations that fail.
To keep this change backwards compatible, we do not send an error to the client, since some clients may currently expect the `error` message to also signal the end of a subscription. This means we are effectively swallowing the error on the recomputation path.
Test plan
---------
Added a couple tests for the new behaviors.

Support computation retries without dumping the cache

---

reactive/rerunner.go

In both branches, lastRun needs to be set before we scheduled or attempt a new run so that the next run has an accurate delay timer.

reactive: fix race/out of order setting for lastRun

---

graphql/parser.go
graphql/server.go

This can be helpful for error reporting which query is failing to be parsed.

graphql: return name/kind on parsing failures

---

graphql/server.go
reactive/rerunner.go
reactive/rerunner_test.go

Removes the lag between making a change and seeing the change appear.
Tested locally with the example application. It's much nicer.

graphql: let all subscriptions immediately after a mutation

---

sqlgen/batch.go
sqlgen/batch_test.go

MySQL <= 5.6 fails to optimize index usage when using the IN clause with tuples.
This works around that behavior by constructing AND/OR clauses that can be optimized.
I verified manually that simple / simple + complex forms do not scan the entire table for mysql 5.6.
See: https://bugs.mysql.com/bug.php?id=31188

sqlgen: change batching scheme to not use tuples

---

diff/diff.go
diff/diff_test.go

When elements are identical in the output, do not re-arrange them. Otherwise, this causes unnecessary diffs to be sent to the client.

diff: do not rearrange identical elements

---

graphql/schemabuilder/reflect.go
graphql/schemabuilder/reflect_test.go
graphql/schemabuilder/types.go

To split large graphql schemas across multiple packages, we need a
mechanism for registering functions on the same type in different
places.
With the approach in this commit, a meta-package can pass the same
schemabuilder.Schema to two different sub-packages that both add fields
to common types.

graphql schemabuilder: allow invoking Object twice to extend types

---

graphql/end_to_end_test.go
graphql/introspection/introspection.go
graphql/introspection/test-schema.json
graphql/parser.go

Allow undefined variable in query

---

diff/diff.go
diff/diff_test.go

They show up in JSON sometimes to encode binary as base64 data. Allow
that.

diff: support diffing byte slices []uint8

---

README.md
graphql/http.go
graphql/http_test.go

This PR provides an http interface to use thunder for those who do not want to use websockets/live queries but still like all of our other sweet features.

Provide a non-live http interface

---

graphql/end_to_end_test.go
graphql/parser.go
graphql/parser_test.go

This PR adds support for checking that non-null operation variables are correctly passed in, fixing #70.
It also adds base support for default values.

Check variable definition in parse step, support default arguments

---

graphql/parser.go
graphql/parser_test.go

This PR changes the parser to parser the query kind/name earlier so that it will show up in case of client parsing errors.

graphql: parse name/kind before variables

---

batch/batch.go
concurrencylimiter/concurrencylimiter.go
concurrencylimiter/concurrencylimiter_test.go
graphql/executor.go

The new concurrencylimiter package lets the graphql executor limit the number
of resolvers that are running at the same time. It integrates with the batch
package to allow resolvers that are joining a batched call to unblock other
resolvers.
All of this is opt-in using the concurrencylimiter.With call. Otherwise
everything behaves like before.

concurrencylimiter: bound number of concurrently running resolvers

---

graphql/parser.go
graphql/parser_test.go

This reverts commit 7828561be8596c2904b42ba681684067466513f4. The reverted commit is technically a breaking change since the old server did not validate these problems.

Revert "graphql: check for required operation variables"

---

graphql/middleware.go
graphql/server.go

Useful for passing arbitrary metadata down. For instance, we can use this to send request ids or trace ids down to the server.
Other ideas for this kind of mechanism are welcome.

graphql: add support for metadata on incoming envelopes

---

README.md

Attempt to address #87. Perhaps we should consider an API change here so that `ComputeSchemaJSON` does not also call `AddIntrospectionToSchema`..
@jonlundy does this help?

readme: attempt to make schema dumper example more clear

---

graphql/schemabuilder/reflect.go
graphql/schemabuilder/reflect_test.go

cc/ @jbicket
It's a little tricky to provide a better message in case the caller is actually intending the parent "source" instead of an arguments struct since the function signature is overloaded. This at least helps with identifying what field is wrong.
Before, this would just panic and not identify the bad field.

graphql schemabuilder: gracefully fail if wrong argument type is passed

---

graphql/server.go

Otherwise, the whole thing panics.
Let's also add a test for this later.

graphql: by default, use passed schema as mutation schema

---

client/package.json
client/src/query.tsx
client/src/tests/query.spec.tsx
client/yarn.lock

This PR fixes a bug we've seen where queries get unsubscribed and then re-subscribed before their data even comes in. This ends up happening because the props to the component change, and this check is faulty. It compares the next props with the query/variables stored in `this.state`, but the state is only ever set when new data comes in.
This means that if the props (even superficially) change before the first data loads, then the component starts over.
We've seen in production that this disproportionately affects queries that are already slow.

Fix <Query> shouldComponentUpdate

---

graphql/executor.go
graphql/introspection/introspection.go
graphql/introspection/introspection_test.go
graphql/introspection/test-schema.json
graphql/schemabuilder/reflect.go
graphql/schemabuilder/types.go
graphql/types.go
graphql/union_test.go

This PR adds graphql union type support. Union types are approximated by using a special marker in a return type, `schemabuilder.Union`. Embedding this marker signals to the schemabuilder that the return type is a one-hot union.
```golang
type GatewayUnion struct {
graphql.Union
// One-hot fields must be pointer type. Also must be anonymous.
*models.Gateway
*models.Vehicle
}
```
An example resolver might look like:
```golang
query.FieldFunc("gateway", func(args struct{ Type GatewayType }) (*Gateway, error) {
if args.Type == GatewayType_Vehicle {
return &Gateway{
Asset: &models.Asset{Name: "b", BatteryLevel: 5},
}, nil
}
return &Gateway{
Vehicle: &models.Vehicle{Name: "a", Speed: 50},
}, nil
})
```

Add union type support

---

sqlgen/reflect_test.go

These tests were failing because they are pointers to structs. They now fail for the right reasons.

go sqlgen: tests were failing for the wrong reasons

---

graphql/schemabuilder/reflect.go

I noticed a redundant parse error for enums.

graphql schemabuilder: remove redundant parse error for enums

---

.travis.yml
sqlgen/integration_test.go

Benchmark output:
```
goos: darwin
goarch: amd64
pkg: github.com/samsarahq/thunder/sqlgen
Benchmark/Read-8         	    5000	    358456 ns/op	    1766 B/op	      45 allocs/op
Benchmark/Create-8       	    2000	    677856 ns/op	    1104 B/op	      23 allocs/op
Benchmark/Update-8       	    2000	    682379 ns/op	    1488 B/op	      30 allocs/op
Benchmark/Delete-8       	    2000	    626050 ns/op	     592 B/op	      16 allocs/op
```

Add benchmarks to SQLGen

---

CHANGELOG.md
fields/descriptor.go
fields/sql.go
fields/sql_test.go
sqlgen/reflect.go

Currently, the only way to make sql.Scanner nullable is either by using the sql.NullBool pattern (where we break up the value into `IsValid` and `Bool`/whatever type).
This is because the single de-reference method can't overwrite the pointer to be a null pointer. We also can't define two methods (one for single de-reference and one for double de-reference), so the developer story starts looking a little messy.
In order to support nullable custom types (for real), we will handle `nil` on behalf of the scanner if it's a pointer.
**Side Effect: Remove `Scanner.Interface()`**
This method was exclusively being used in test at this point and won't properly set `nil` for pointers. In order to prevent bad behavior, we need to remove this method.

go sqlgen: support nullable (pointer) sql.Scanners

---

graphql/schemabuilder/types.go

Changed the embeddable Union type to appropriate type in the GoDoc comments.

doc comments corrected for schemabuilder union

---

fields/sql.go
fields/sql_test.go

See https://github.com/samsarahq/thunder/pull/142/files#diff-ec296ed9b760f4157d5adf8255a5c5c8L102
I looked through our other scalars, and we handle the rest of them (including bytes with our own behavior). This unfortunately couples us back to MySQL.

go fields: handle time like we did before, with mysql.NullTime

---

internal/fields/sql.go
sqlgen/reflect.go
sqlgen/reflect_test.go

Currently binlog tester does not match int32 filter value against a int64 column, for example. It doesn't support custom type either. This fixes both.

go sqlgen: binlog testers should compare driver.Values

---

internal/fields/descriptor.go
internal/fields/sql_test.go

This PR fixes a bug where we don't use a pointer to struct when verifying that the input type is a valid sql type. This occurs when the method receiver is a pointer AND the type passed is a pointer. The cases for non-pointer method receivers already works fine.

fields: fix sql type validation for pointer receiver methods

---

internal/reflect.go
internal/reflect_test.go
livesql/integration_test.go
livesql/live.go
sqlgen/matcher.go

We have UUIDs which use or convert to `[]byte`. Both livesql and the batcher rely on comparable/hashable values (values that are put into a `map`) to work and panic otherwise. This means that we can't use those custom types with livesql or batching.
The `ToArray` function has been used for creating hashable/comparable arguments in the past. Renamed it to be more explicit, and also handle `[]byte` arguments, converting them into strings.
The primary use-case for this PR is to support UUIDs. We also get support for anything else that turns into `[]byte`.
The reason we want to serialize our arguments/filters is because (unfortunately) we support type aliases in our filters, and therefore allow you to query a `int64` with `int`/`int8`/etc. In order to maintain backward compatibility there, we …

go {livesql,sqlgen,internal}: support []byte arguments for live queries

---

livesql/binlog.go
logger/logger.go
sqlgen/reflect.go

1. Allow for the destination of error output to be customized
2. Provide table and column information when parsing fails in `livesql` and `sqlgen`

sqlgen/livesql: Improve error logging

---

CHANGELOG.md
ci/docker-compose.yml
internal/fields/reflect.go
internal/fields/reflect_test.go
internal/fields/sql.go
internal/integrationtest/helpers.go
internal/integrationtest/implicitnull_test.go
internal/testfixtures/db.go
livesql/integration_test.go
sqlgen/integration_test.go
sqlgen/reflect.go

Summary: Adds support to sqlgen to convert "Zero" value model fields to NULL in 
the database.  This only needs to be applied when inserting a value to the 
database because when we read from the db NULL values are noop (leaving the 
zero value).
I put some cleanups in the PR as well, would be easy to pull them out if we want.
Additionally, I wrote tests for the "Main" use cases, but I'm very open 
to add tests for other edge cases, let me know and I'll add them.

go sqlgen: Add support for converting "Zero" value fields to NULL in the db

---

CHANGELOG.md
internal/fields/sql.go
internal/fields/sql_test.go
sqlgen/integration_test.go

Because we sometimes might want to use non-pointers for protobuf, check our non-pointer types.
Test plan:
- Create benchmark for the above - maybe we should have benchmarks per supported value
- Run simulation traffic if the benchmarks look significantly different (more than 5%)

go fields: explicity support non-pointer marshalers

---

diff/diff.go
diff/diff_test.go

When passed an array with nil values, `diff.Diff` would panic. This no longer happens.
Updated unit tests to add breaking case, the diff seems reasonable. The tests also worked without updating the tests file, which means there is no breaking behavior here.

go diff: don't panic on nil array value

---

graphql/server.go

Helpful for debugging c.handle errors logged. As a follow up, we should
fix up this code path so that errors can be handled by the client code.

graphql: oops wrap json errors with message

---

graphql/middleware.go
graphql/server.go

Allow middlewares to mutate the previous computation output, for altering the diff sent back.
Also expose whether this is an initial computation to the middlewares.

graphql: make previous computation mutable by middlewares

---

sqlgen/example_test.go

This documents the ability to override sqlgen values with struct tags
for binary, string and json.

Add example for struct tag overrides

---

CHANGELOG.md
graphql/schemabuilder/reflect.go
graphql/schemabuilder/reflect_test.go
vendor/github.com/samsarahq/go/oops/LICENSE
vendor/github.com/samsarahq/go/oops/README.md
vendor/github.com/samsarahq/go/oops/doc.go
vendor/github.com/samsarahq/go/oops/oops.go
vendor/vendor.json

See commits. I added some unit tests.

diff key must be scalar

---

graphql/executor.go
graphql/http.go
graphql/server.go

This PR exports `ErrorCause` which allows client code to extract the root, unwrapped error for checking. It is useful for checking root case, e.g.:
```golang
if graphql.ErrorCause(err) == context.Canceled {
// ...
}
```

graphql: export ErrorCause helper

---

graphql/http.go

Summary; the current HTTP interface is hardcoded to only handle Queries, I changed it so it would also handle mutations

Allow http interface to handles mutations

---

CHANGELOG.md
sqlgen/reflect.go
sqlgen/reflect_test.go

Add BuildStruct method back into sqlgen so we can parse
binlog row event the same way we scan from MySQL driver.
This was removed in https://github.com/samsarahq/thunder/pull/166.

go sqlgen: add BuildStruct

---

livesql/marshal.go
reactive/rerunner.go

This is a hack to support binlog invalidation outside livesql.
Two commits:
```
go reactive: add dependency callback
We want to move binlog invalidation out of sqlgen/livesql.
By adding a hook in AddDependency, we can add a child
resource in the computation node that caches SQL result,
and kick off custom invalidations.
```
```
go livesql: expose FieldToValue
We'd like to parse driver.Value from thunderpb.Field added
in AddDependency calls in DependencyCallback.
```

hook in AddDependency

---

livesql/live.go
livesql/marshal.go
livesql/marshal_test.go
reactive/rerunner.go

We see keeping a dependency set of protobuf message uses
a lot of memory. We think building protobuf messages has
significant overhead. Instead, we will export a QueryDependency
type in livesql, and it will be up the user to call method in livesql
to turn them into protobuf messages.

go reactive: dependency does not need to be serializable

---

CHANGELOG.md
graphql/schemabuilder/pagination.go
graphql/schemabuilder/reflect.go
graphql/schemabuilder/types.go

Don't require PaginateFieldFunc for creating field funcs. Rather, FieldFunc takes in a Paginate option.

Make pagination an option for FieldFunc

---

sqlgen/integration_test.go

This adds a benchmark for "native" (go stdlib) sql queries to compare our other benchmark against. It might also be worth moving the blank struct allocation out of the loop.
```
Benchmark/Read-2 	           10000	    159543 ns/op	    1665 B/op	      43 allocs/op
Benchmark/Read_Where-2         	    5000	    285107 ns/op	    2337 B/op	      56 allocs/op
Benchmark/Create-2             	    1000	   1956704 ns/op	    1120 B/op	      26 allocs/op
Benchmark/Update-2             	    5000	    261100 ns/op	    1496 B/op	      32 allocs/op
Benchmark/Delete-2             	    5000	    237507 ns/op	     808 B/op	      25 allocs/op
BenchmarkSql/Read-2            	   10000	    145322 ns/op	     932 B/op	      25 allocs/op
BenchmarkSql/Read_Where-2      	    5000	    260387 ns/op	    1136 B/op	      30 …
```

go sqlgen: add baseline benchmark running against native sql

---

graphql/connection_test.go
graphql/introspection/testdata/TestComputeSchemaJSON.snapshots.json
graphql/schemabuilder/pagination.go
graphql/schemabuilder/reflect.go
sqlgen/integration_test.go

When pointers are passed into buildFunction it gets things wrong.
When determining if the function is a ptr-func, it checks to see if the ptr representation of a type
matches what is passed in as an argument to the function.
Because we are passing in a pointer, that pointer representation ends up being a dual pointer.
Added an error so that we can't shoot ourselves in the foot this way again.
Also in this PR:
- Nodes on connections are marked as non-null

Bugfix: sort/filter fields now support pointer sources

---

graphql/end_to_end_test.go
reactive/rerunner.go

Add a delay to wait after hearing a change was made, before reading that change by rerunning.

reactive: delay rerunner in order to emulate write-then-read behavior

---

CHANGELOG.md
graphql/defaultargs_test.go
graphql/schemabuilder/input.go
graphql/schemabuilder/reflect.go
graphql/testdata/TestDefaultArgs.snapshots.json

Summary: Adds support for graphql parameter fields to be noop fields.
Previously if you wanted to add a non-pointer field as a new input arg
to one of your functions this would break all existing callers (since 
they would not have the proper field).  Now if you have an existing
input struct like:
```
type Input struct {
Arg1 string
Arg2 string
}
```
You can safely add a new type like so:
```
type Input struct {
Arg1 string
Arg2 string
Arg3 string `graphql:",optional"`
}
```
And the Arg3 string will get filled with "" if no args are provided.

go graphql: Add support for Default/ZeroValue parameter defaults

---

graphql/http.go
graphql/http_test.go

I would like to add support of setting more relevant than `text/plain` Content-Type header for GraphQL. Regarding [specification](https://graphql.org/learn/serving-over-http/), response should has JSON format, so, the more suitable Content-Type is `application/json`.
This PR replaces using `http.Error` with `w.Write` for sending output to the client.
Why I think it is important.
Overriding Content-Type header inside `http.Error` is not only one thing, made me do this PR. In order to pass JSON to `http.Error`, you have to convert it to string. This is totally redundant operation for this case. Moreover, `http.Error` adds additional `\n` (because of `fmt.Fprintln()`) to each response of service, based on this framework. Though there is not any conventions in specifications of …

Add support of setting proper Content-Type header, small optimisation

---

graphql/end_to_end_test.go
graphql/http.go
graphql/schemabuilder/perf_test.go
graphql/server.go
livesql/example_test.go
livesql/integration_test.go
reactive/rerunner.go
reactive/rerunner_test.go

Turns out reruns blocked call to Invalidate().

graphql, reactive: add flag to spawn goroutine

---

CHANGELOG.md
graphql/batch_executor.go
graphql/batch_scheduler.go
graphql/connection_test.go
graphql/end_to_end_test.go
graphql/executor.go
graphql/executor_test.go
graphql/reactive_test.go
graphql/schemabuilder/function.go
graphql/schemabuilder/output.go
graphql/schemabuilder/pagination.go
graphql/schemabuilder/perf_test.go
graphql/schemabuilder/reflect_test.go
graphql/testdata/TestConnection.snapshots.json
graphql/testdata/TestDefaultArgs.snapshots.json
graphql/testdata/TestTextMarshaling.snapshots.json
graphql/types.go
graphql/union_test.go
graphql/writer.go
internal/testgraphql/executor.go
internal/testgraphql/snapshotter.go
reactive/ctxmutex_test.go
reactive/graph.go
reactive/rerunner.go
reactive/rerunner_test.go

Summary: Adds a new Executor option for Graphql execution to thunder.  This new
entrypoint has the ability to control the concurrency of requests through a 
"Scheduler" interface which owns how "ExecutionUnits" are executed on the graphql
graph.  In addition the new executor treats batches as a top-level concern, this 
makes it much easier to slot in graphQL batchFieldFuncs in a subsequent PR.
In the process of adding this new feature, there were a couple changes/fixes
that needed to go in to help with the migration:
- Fix passing SelectionSet into functions
- Change Object.Key from a Function to a fully-formed graphql.Field
- Add "External" flag on graphql.Field to control external concurrency.
- Clear reactive cache computations when a request errors.
- Fix Union type __typename fields …

go graphql: Add BatchExecutor for controlled concurrency and Batching Capabilities

---

graphql/executor.go

This PR adds Unwrap support to the pathError type, following the design from https://go.googlesource.com/proposal/+/master/design/29934-error-values.md

graphql: add Unwrap support

---

graphql/http.go

Summary: I don't think this executor is used anywhere, but I'd rather
have a common change across the board to use the new ExecutorWrapper
api.

go graphql: Add ability to override HTTP graphql executor

---

CHANGELOG.md
graphql/batch_executor.go
graphql/batch_test.go
graphql/connection_test.go
graphql/end_to_end_test.go
graphql/executor.go
graphql/executor_test.go
graphql/http.go
graphql/introspection/introspection.go
graphql/reactive_test.go
graphql/schemabuilder/batch.go
graphql/schemabuilder/function.go
graphql/schemabuilder/output.go
graphql/schemabuilder/perf_test.go
graphql/schemabuilder/reflect_test.go
graphql/schemabuilder/types.go
graphql/server.go
graphql/types.go
graphql/union_test.go
internal/testgraphql/snapshotter.go

Summary: Adds support for running fieldFuncs as a "Batch" instead of one at a time. 
The API surface of this forces passing in a Fallback/Non-batch function that has 
the same signature as the batch function.  This is mostly for the transition period,
eventually we'll go full-batch.

go graphql: Add BatchFieldFuncs to new Executor

---

graphql/batch_executor.go

Summary: I wrote a graphql tree flattening function that would convert
an output node into a JSON tree of map[string]interface{},
[]interface{}, etc.  We didn't use it because we thought we wouldn't
necessarily need it (we could do JSON marshal/unmarshaling).  Since 
the thunder/diff package heavily depends on the map[string]interface{}
type structure to function properly this commit unwraps the new executor's
graphql result.

go graphql: Use flattening function for new executor results

---

graphql/batch_executor.go
graphql/executor_test.go

Summary: Accidentally wasn't using the proper index for list error paths.
Caught this error when running through all our production
snapshots.  Wrote a test that fails before the executor change and
passes after the change.

go graphql: Properly index paths for list errors in batch executor

---

graphql/batch_executor.go
graphql/batch_test.go

Summary: Fixes a bug that would occur when a batchFieldFunc would return
less objects than were passed in.  Adds a test which failed before and
passes afterwards.

go graphql: Fix bug with passing back nils/empty results for batchFuncs

---

graphql/batch_executor.go
graphql/batch_test.go
graphql/schemabuilder/batch.go

Summary: Added tests to validate that List and Union types worked
properly with batch functions.  Found that there were some odd edge
cases with batches that required a few extra checks.  In addition to the
extra checks we need to be able to support Non-Nil List types to have
1:1 support with the existing list responses (which must be non-nil).
We make an exception to batch list responses to support returning
nil/non-valid values and converting them to a Zero-sized list.
Added tests for List and Union to validate that everything works.
Only grey area type now is enum types which are not fully functional in
batch & non-batch contexts. but solving this might be a bit more trouble
than it is worth.

go graphql: Fix Nil List & Union responses in Batches

---

graphql/batch_test.go
graphql/schemabuilder/batch.go
graphql/schemabuilder/types.go

Summary: Adds support for marking a BatchFieldFunc as "NonNullable". We
don't have the ability to enforce this explicitly through the function
signature, but we can enforce it by validating that responses are being
passed back properly for every node we passed in.  If we see a mismatch
we fail the entire query.
This allows us to have parity with the current non-nullable fieldFuncs
we have right now.  I've added some tests to validate that we fail if a
nil result is returned, and for the happy cases of having non-nil
strings and enum values.

go schemabuilder: Allow marking batchFieldFuncs as "NonNullable"

---

reactive/rerunner.go
reactive/rerunner_test.go

Summary: Removes a cleanAll func call whenever we get an error.

go reactive: Don't cleanAll whenever we get an error

---

reactive/rerunner.go
reactive/rerunner_test.go

Summary: Whenever we get a retry sentinel error we want to throw away
the current calculations we have to get a clean slate for the next run.
This is required to rollout the new graphql Executor which has a
possibility of caching promises that stored an error (instead of the
result we want).

go reactive: Reset reactive cache on every run.

---

graphql/batch_scheduler.go

Summary: Noticed that if multiple queries called into the batchScheduler
at the same time we would potentially have issues with concurrency.
This commit creates a sub "runner" struct that holds on to the wg state
instead of the top-level goroutine scheduler.

go graphql: Make batchScheduler thread-safe

---

batch/index.go
graphql/batch_test.go
graphql/schemabuilder/batch.go
graphql/schemabuilder/reflect_test.go

Summary: Introduces a batch.Index type that we can optionally use in
batchFieldFuncs.  This is to make it obvious that we're using an index
and not necessarily a key or Id.

go graphql: Add support for using batch.Index as key for all batchFieldFuncs

---

graphql/batch_executor.go
graphql/batch_test.go

Summary: There was an edge-case where we'd schedule another round of
useless work for empty list responses.  This fixes the problem by
stopping the unwrapping if we have no sources/destinations to use.

go graphql: Short-Circuit execution if no sources

---

graphql/batch_executor.go
graphql/batch_executor_test.go

Summary: Updates the batch executor to treat non-batch non-expensive
field funcs as though all execution was similar to a batch.  This means
we run the resolvers individually, but schedule the next set of work as
if the results came from a batch.  Previously we would schedule the next
set of work individually, which meant if we had deep graphs of non-expensive
field funcs we'd spawn a lot of goroutines.

go graphql: Execute non-expensive work similar to a batch.

---

graphql/errors.go
graphql/errors_test.go
graphql/server.go

We want to be able to extract stack traces from safeErrors. To do this, we're adding an `inner` field to the struct, and implementing `Unwrap` to extract this in order to get to an error type that provides a stack trace.
I've also moved errors out to errors.go for cleanliness.

Implements Unwrap for SafeErrors

---

reactive/rerunner.go
reactive/rerunner_test.go

Summary: In order to migrate slowly off of reactive.Cache we need
the ability to gate a slow rollout of removing the cache.  This commit
adds a new function that exposes the ability to delete/clear the
reactive cache.

go reactive: Add PurgeCache function

---

sqlgen/db.go
sqlgen/integration_test.go

When we use UpdateRow, we fail to check if the shard filter is in the
where columns. If the shard is part of PK, the column and value is
added to as part of the columns in the where component of the query.
As a result, we should check both the where and the regular columns
for the shard filter when we update a row.

sqlgen: WithShardLimit bug when filter is part of pk

---

graphql/batch_test.go
graphql/schemabuilder/batch.go
graphql/schemabuilder/output.go
graphql/schemabuilder/types.go

Summary: Adds an entrypoint for batchFieldFuncs that does not require a
"fallback" method to be registered.  This will not work with the old
executor, but, we're in the process of deleting the old executor so it
should be fine.

go schemabuilder: Add BatchFieldFunc entry point (no fallback)

---

graphql/batch_executor.go
graphql/executor.go
graphql/types.go

Summary: There were some issues with passing the information about whether
to batch a function in the selection.UseBatch parameter. Sometimes it just
wouldn't get set for unknown reasons (after the UseBatch func was replaces
with an "Always on" function).  Instead of going through and finding deep
hidden meaning in go structs, this commit just changes the logic for
determining batch execution to call into the usebatchFunc function in the
execution path, and deletes the selection.UseBatch type.
In order to do this we needed to add a "useBatch" option to the WorkUnit so 
we wouldn't accidentally schedule work to be batched, then run it sequentially. 
(if the feature flag changed mid-query).

go graphql: Remove selection.UseBatch option

---

graphql/benchmark_test.go
graphql/connection_test.go
graphql/schemabuilder/pagination.go
graphql/schemabuilder/types.go
internal/filter/filter.go
internal/filter/filter_test.go

Added batch filtering and fallback methods for filtering during pagination
To run the tests, use `GOMAXPROCS=1 /Users/arshiamalkani/co/backend/opt/go1.11.5/bin/go test -benchmem -run=^$ github.com/samsarahq/thunder/graphql -bench=.`
Benchmark Test results
```
BenchmarkFiltersBatched10Items             30000             40715 ns/op           16149 B/op        247 allocs/op
BenchmarkFiltersNotBatched10Items          30000             58969 ns/op           15419 B/op        245 allocs/op
BenchmarkFiltersBatched100Items            10000            120814 ns/op           69603 B/op        930 allocs/op
BenchmarkFiltersNotBatched100Items          3000            436085 ns/op           68804 B/op       1064 allocs/op
BenchmarkFiltersBatched1000Items            2000           1114082 ns/op …
```

Batching Pagination Filters

---

graphql/batch_executor_test.go
graphql/end_to_end_test.go
graphql/schemabuilder/batch.go
graphql/schemabuilder/function.go
graphql/schemabuilder/pagination.go
graphql/schemabuilder/reflect_test.go
graphql/schemabuilder/types.go

Add a field func option to mark a field func as "expensive".
Previously, Thunder would assume that any field func accepting a "context" parameter must be expensive and so should be executed concurrently.
The new behavior is to assume that a field func is inexpensive unless the Expensive option is set explicitly.

go graphql/schemabuilder: add Expensive field func option

---

diff/diff.go
diff/diff_test.go

Summary: Noticed and brought up by Edwin last week. This bug has existed
for a long time.  The way it would manifest, is that when a field would
get replaced with a "Nil" value in the execution graph, instead of
diffing the value and returning "nil" as the new value, we were using
the result of a failed cast `newVal, ok :=
val.(map[string]interface{})`.
The `newVal` would be an empty map (instead of the "nil" value we really
wanted).  This would lead to weird behavior, where, on an update,
instead of returning a nil value for something like current driver, we'd
return an empty object instead.

go diff: Fix long-standing diffing bug 

---

graphql/batch_executor.go
graphql/connection_test.go
graphql/executor.go
graphql/schemabuilder/batch.go
graphql/schemabuilder/pagination.go
graphql/schemabuilder/types.go

(1) Builds the batch function with fallbacks correctly for paginated filters. This also means setting it to be nonullable in all cases
(2) Uses the SafeExecuteBatchResolver and SafeExecuteResolver for pagination to handle panics better 
(3) Allows you to pass in optional arguments for options when working on a filter. This is useful for the BatchFilterFieldWithFallback where you can set it to Expensive

Error Handling for Batched Pagination Filters

---

graphql/benchmark_pagination_test.go
graphql/connection_test.go
graphql/schemabuilder/pagination.go
graphql/schemabuilder/types.go

Batches the paginated sorts by 
(1) Run the paginated sorts batched
(2) Run the paginated sorts not batched and executed serially, which is useful if we aren't making expensive operations
(3) Run the  paginated sorts not batched but with an expensive flag to spawn a goroutine per node. It detects if it is expensive if it has a ctx passed in. 
```
BenchmarkSortsBatched10Items                       50000             39933 ns/op           15834 B/op        246 allocs/op
BenchmarkSortsNotBatched10Items                    50000             29063 ns/op           12065 B/op        213 allocs/op
BenchmarkSortsNotBatchedExpensive10Items           50000             34620 ns/op           12385 B/op        213 allocs/op
BenchmarkSortsBatched100Items                      10000            116631 ns/op …
```

Batching Paginated Sorts

---

graphql/schemabuilder/batch.go
graphql/schemabuilder/function.go
graphql/schemabuilder/pagination.go
graphql/schemabuilder/reflect_test.go

Summary: We think this caused some issues (we just had an outage that's hard to pinpoint, this change is the most suspicious), we're making it a noop for now while we investigate further.

go schemabuilder: Make expensive option a noop

---

graphql/schemabuilder/batch.go

BatchFieldFuncWithFallback was dropping the Expensive flag
when building the fallback field.  Pass that flag down
so the fallback field respects it.

go graphql/schemabuilder: fix expensive option for BFF fallback

---

graphql/schemabuilder/batch.go
graphql/schemabuilder/function.go
graphql/schemabuilder/pagination.go
graphql/schemabuilder/reflect_test.go

This reverts commit 34dfd659753f186b319821cc0669f51a3e513bcc.
I believe all the field funcs are now marked with the
Expensive option, so we can re-enable this functionality.

Revert "go schemabuilder: Make expensive option a noop"

---

graphql/schemabuilder/build.go
graphql/schemabuilder/output.go
graphql/schemabuilder/reflect_test.go
graphql/schemabuilder/schema.go
graphql/schemabuilder/testpackage/types.go

Prevent types from colliding in name.

graphql: prevent type names from being duplicates

---

vendor/golang.org/x/sync/LICENSE
vendor/golang.org/x/sync/PATENTS
vendor/golang.org/x/sync/errgroup/errgroup.go
vendor/vendor.json

Thunder pagination now depends on golang.org/x/sync/errgroup,
so add this to the vendored dependency list.

vendor: add missing errgroup dependency

---

graphql/connection_test.go
graphql/introspection/testdata/TestComputeSchemaJSON.snapshots.json
graphql/schemabuilder/pagination.go

FilterText allows us to query specific fields when we make paginated requests. However, we run the filterText against all the filters. FilterTextOptions allow us to specify which filters to run it against. The api now would look something like
```
filterByCan: innerConnectionWithFilter(filterText: "can", filterTextField:["foo","wug"],first: 5, after: "") 
```

FilterTextOptions to Select Filters

---

graphql/connection_test.go
graphql/schemabuilder/input.go
graphql/schemabuilder/output.go
graphql/schemabuilder/pagination.go
graphql/schemabuilder/types.go
graphql/testdata/TestConnectionManual.snapshots.json

For the Fast Pagination Indices project, we want to use manual pagination such that the index reader service can handle the pagination logic and only return the data going to be displayed. As endpoints get moved over to the indexing solution, we want a nice way to feature flag them. This means that we want to register both the field func (that uses indices and is manually paginated) and the fallback, which requires a thunder change. 
RFC reference
https://paper.dropbox.com/doc/RFC-Pagination-Indices--Ajk_EnByDy_fw8S6SrVjgxhAAg-E948ZaMsM7Ls6ZAWtpT5e

Manual Pagination With Fallback

---

graphql/connection_test.go
graphql/testdata/TestConnectionCursor.snapshots.json

There aren't any unit tests for the cursors, so I added them. This is useful since the manual pagination solution needs to match the way thunder works.

Added more pagination tests

---

graphql/connection_test.go
graphql/schemabuilder/pagination.go
graphql/testdata/TestConnectionManual.snapshots.json

You can set pages inside of something manually paginated if you want or set it to an empty list if that information isn't used. This keeps the apis between manual pagination and pagination the same.

go thunder: set pages in pagination info

---

graphql/connection_test.go
graphql/schemabuilder/pagination.go
graphql/testdata/TestConnectionManual.snapshots.json

It was creating the fallback function, but without the args (filter and sort fields, expensive flag, pagination flag, etc). It passes on the information now

Manual Pagination Fallback Function Issue

---

graphql/errors.go
graphql/server.go

Make a helper function for calculating the
sanitized error message public so we can use
it outside of Thunder.

go graphql: expose SanitizeError helper

---

graphql/batch_executor.go
graphql/batch_executor_test.go
graphql/schemabuilder/batch.go
graphql/schemabuilder/function.go
graphql/schemabuilder/pagination.go
graphql/schemabuilder/types.go
graphql/types.go

Summary: Adds the ability to control the number of concurrent work units
we'll create for batch and non-expensive fields.  This allows us to control
how big batches get and allows us the ability to split these batches into
smaller sub-executions (sometimes we get diminishing returns from batches
after they get to a certain size).

go graphql: Add ConcurrencyController option for batch and non-expensive execution

---

sqlgen/db.go
sqlgen/db_test.go
sqlgen/errors.go
sqlgen/errors_test.go

Adding more information about the query on a dynamic limit failure is helpful for understanding why a limit failed in the first place.
This PR adds the query clause and arguments to the error returned to a client on a DynamicLimit failure.

sqlgen db: more detailed error for DynamicLimit failures

---

graphql/errors.go
graphql/executor.go
graphql/executor_test.go
graphql/export_test.go
sqlgen/errors.go
sqlgen/errors_test.go

Adding Reason function to errors so it is compatible with https://github.com/samsarahq/go/pull/12

go errors: adding Reason function to errors for user  readibility

---

graphql/executor.go
graphql/executor_test.go
graphql/parser.go
graphql/parser_test.go
graphql/types.go

Expose these two types on selections so that middleware can read
them for debugging/tracing.

graphql: expose UnparsedArgs and ParentType for traceability

---

graphql/executor_test.go
graphql/parser.go

Fix a bug where flatten drops arguments if it needs to merge
two selections. Also add a test for this behavior.

graphql: fix issue where Flatten drops args

---

graphql/executor_test.go
graphql/parser.go

Fix an issue where ParentType was also not being merged properly
in Flatten. Add a test.

graphql: include ParentType in Flatten

---

graphql/connection_test.go
graphql/schemabuilder/pagination.go

This adds a PostProcessOptions that externally managed paginated endpoints need to return and optionally fill options of. This lets Thunder perform additional operations on the output based on the turned-on flags.
The first flags, added in this PR, are `ApplyTextFilter`, which will apply a text filter on the output, and `SetPageInfo`, which will set the page info based on the output.

Pagination: add PostProcessOptions

---

federation/schema/kitchen_sink_test.go
federation/schema/merge_schemas.go
federation/schema/normalize.go
federation/schema/schema.go
federation/schema/schema_test.go
federation/schema/testdata/TestBuildSchemaKitchenSink.snapshots.json
graphql/introspection/introspection.go
graphql/schemabuilder/schema.go

Federation Part 1: Schema Merging
Merging between versions (intersection)
During an update to a new version, we want to have a version of the schema that is compatible with both schemas. In this case, we want to get the intersection between the two schemas so that we know what we are running is compatible with both schemas. 
Merging between schemas (union)
The gateway needs to be able to take all the schemas from separate servers and generate a merged version that is compatible with all schemas and annotated with federation info (ie which server has which field func) so that it can generate a query plan

Federation Schema Merging 

---

federation/normalize.go
federation/normalize_test.go
federation/schema/schema_test.go

Normalize flattens queries into easy-to-wrangle shapes.
TODO: Use normalize for query execution in the non-federation codepath.

federation: add normalize implementation

---

graphql/server.go

Summary: Noticed this as a memory leak when we would upload a lot of
images through mutation endpoints.  The subscriptions for mutations are
never cleaned up, and the memory from the request (an image) would
remain in-memory until we'd kill the websocket connection.
Tested this by uploading a bunch of images and monitoring the heap usage.
Before change:
After change:
(you can't even see the spike, we miss it)

go graphql/server: Close Mutation subscription after execution

---

graphql/batch_executor.go
graphql/directive_test.go
graphql/executor_test.go
graphql/parser.go
graphql/testdata/TestDirectivesWithFragments.snapshots.json

We have verified the directive does not work on the following query.
query {
items {
id
...X
}
}
fragment X on Item {
name @skip(if: true)
}`
This commit fixes the bug.

Fix a bug where directive on fragment selection has no effect.

---

graphql/introspection/introspection.go
graphql/introspection/testdata/TestComputeSchemaJSON.snapshots.json

To conform to the graphql spec, the @include and @skip directives should
take in a Boolean!, not a Boolean.
This fixes a behavior where we were incorrectly reporting the schema for
these directives as nullable, which would cause clients that used that
schema for type generation to believe that they could pass in null.
If null was passed in, this would cause an entire query to fail.
This is a a backwards-incompatible change for clients using the
generated schema, but is being made as it conforms to the graphql spec.
https://spec.graphql.org/June2018/#sec--skip
https://spec.graphql.org/June2018/#sec--include

graphql introspection: make @include and @skip directive if non-null

---

federation/executor.go
federation/executor_test.go

This supports us in parsing the plan and executing the query on multiple services. We can split up the query and run it on different schemas or multiple schemas, but not support nested queries that are on separate schemas. 
This is a stacked PR, so only the last two commits are new.

Federated Executor Without Nested service calls

---

federation/executor_test.go
federation/server.go

The unparsed args are sent in the request, and parsed in the corresponding service before the subquery is run. If any args are missing, the error is correctly bubbled up to the origional requ

Federated Executor: Support Args

---

federation/schema.go
federation/schema_test.go

In the args of a field func, we should be able to pass an enum in and have it parsed as a valid type. This is something thunder already supports in a nonfederated world, so we would like to continue to support it with federation.

Federation: Schema parsing where an enum as input object 

---

federation/executor.go
federation/executor_test.go

This allows us to query downstream gqlservers with subqueries that are not nested on the root queries. We look at the previous stage's query results to key the keys and structure the subqueries to look like the example below. That means if a nested field is on a separate gqlserver, we can parse that query and resolve it correctly
```
__federation {
ObjectName(keys){
...subQuery
}
}
``

Federated Executor: Query with multiple servers and federated keys

---

federation/executor.go

On initialization, the federated executor makes introspection queries to fetch the schema in some cases. We need to pass optional args through here too before it makes the query.

federation: executor initialization gets optional args

---

federation/planner_test.go
federation/schema.go
federation/schema_test.go

Make convert versioned schema a public method so that we can use it in a custom schema syncer to merge the schemas.

federation: convertversionedschema is public

---

federation/executor.go
federation/executor_test.go
federation/kitchen_sink_test.go
federation/planner.go
federation/planner_test.go
federation/schema.go
federation/testdata/TestBuildSchemaKitchenSink.snapshots.json
graphql/schemabuilder/schema.go
graphql/schemabuilder/types.go
graphql/types.go

A federated server can have multiple keys. We pass only the necessary keys to each service by checking what keys that federated schema knows about.
(This is the same PR as https://github.com/samsarahq/thunder/pull/375)

Federation: Support multiple federated keys

---

federation/customexecutor_test.go
federation/executor_test.go
federation/kitchen_sink_test.go
graphql/schemabuilder/function.go
graphql/schemabuilder/schema.go
graphql/schemabuilder/types.go

When we create a an object that can be federated, we use to have to specify a function to expose certain fields 
```
user := s1.Object("User", User{})
user.Federation(func(u *User) *User {
return u
})
```
but now we can pass in an option to the object to autogenerate this function in the schema
```
user := s1.Object("User", User{}, schemabuilder.RootObject)
```
We want developers to add this so we are aware of what objects are federated and what the root types are instead of making everything a federated object.

Simplify api for federating a object 

---

federation/executor_test.go
federation/server.go

Added tests for mutations, preventing multiple mutations, and error handling. Also fixed a bug so that the error gets propagated back to the user correctly.

Federation: Error handling tests and bug fix

---

federation/customexecutor_test.go
federation/executor_test.go
federation/metadataexecutor_test.go
federation/schema_syncer.go

So that we can pass metadata to the introspection query.

IntrospectionSchemaSyncer: add a queryMetadata field to the syncer

---

federation/merge_schemas.go
federation/planner_test.go
federation/schema.go
federation/schema_syncer.go
federation/schema_syncer_test.go
federation/schema_test.go

This makes introspectionQueryResult public so that we can unmarshal schemas without having to copy over types.

federation: make introspectionQueryResult public

---

federation/executor_test.go
graphql/schemabuilder/function.go

In federation, we want to support shadow field funcs. This autogenerates a field to construct the shadow object from the args such that we can run a subquery. We had a bug in which it wasn't correctly reading the args, which gets fixed and tested here.

Shadow FieldFunc

---

livesql/live.go
sqlgen/db.go
sqlgen/db_test.go
sqlgen/reflect.go

In this commit we add the ability to instrument a connection
with a boolean that, when enabled, will have a query panic
when no index is present in a sql explain for that query.
We also add the ability to bypass this check on any given query
in SelectOptions. Additionally we add some thin wrappers to our
query functions to set this option.
This will permit us to enable this check in
tests and have people explicitly make full table scan queries
when they fully intend to.
Implementation detail:
We check both key and possible keys since there are times where key
will be non-null (eg PRIMARY) while possible keys is null, and also
times when key is null, but possible keys is not null (eg when
mysql chooses a full scan despite the presence of an index due to small
table size)

go sql: add option to panic on non-indexed queries

---

federation/executor_test.go
federation/kitchen_sink_test.go
federation/schema.go
federation/schema_syncer_test.go
graphql/schemabuilder/schema.go
graphql/schemabuilder/types.go

We initially had a function called FederatedFieldFunc to create the object, but we needed to ensure that you couldn't add that to anything. It's intended to be only used when we construct the shadow object, and that the name always matched with an object on the federated server. This felt brittlle and easy to use incorrectly, so this change allows us to combine the federated field func with the shadow object creation.
When we create a object, we can tell the schema builder it is a ShadowObject to register it in the schema, but we can also also create a custom shadow object that allows us to write a function to construct the shadow object given the keys. This means that if the key is just an id, we can make a database call to fetch the full object insteadd of passing the entire object …

Federation Custom Shadow Object

---

federation/schema_syncer_test.go
graphql/schemabuilder/input.go

Tests adding and deleting a federated key, and all the states in between that process. This included places where the server has an updated version, but the gateway hasn't updated yet. We do have to make sure that when deleting a field, all the shadow objects stop asking for it. Similarly, we have to make sure that when adding a field, the root object knows about it before the shadow objects know about it.

Federation: Testing adding and deleting keys

---

federation/executor_test.go
federation/kitchen_sink_test.go
federation/planner_test.go
federation/schema.go
federation/testdata/TestBuildSchemaKitchenSink.snapshots.json

Enforces that a field can not return an object if it is a shadow type. This ensures that when a field func returns an object, we can query any field on that object and the client doesn't have to be aware of which ones are on federated servers. This also helps enforce that we can only federated field funcs, and that all queries for fields on the struct are responded to by the server with the root object.

Federation Shadow Type Validation

---

CHANGELOG.md
sqlgen/db.go
sqlgen/db_test.go
sqlgen/mysql.go
sqlgen/mysql_test.go
sqlgen/reflect.go
sqlgen/reflect_test.go

Current sqlgen API only allows inserting one row at a time which makes running large backfills very time consuming.
The intention of the batch API is to allow running backfills at a faster rate

sqlgen Add batch insert API support to sqlgen

---

batch/batch.go
batch/batch_test.go

Previously line 130 panicked with the error "interface{} is nil, not *batch.batchContext" if `Invoke` was called without calling `WithBatching` on `ctx`, so the intended error message was not printed. This change ensures the correct panic message is printed, for easier debugging.

batch: fix panic when context missing WithBatching

---

federation/customexecutor_test.go
federation/executor_test.go
federation/kitchen_sink_test.go
federation/schema.go
federation/schema_syncer_test.go
federation/testdata/TestBuildSchemaKitchenSink.snapshots.json
graphql/schemabuilder/schema.go
graphql/schemabuilder/types.go

* Removes shadow and root objects. We moved the generation of these functions elsewhere. The motivation for this is that we want the objects on two different servers to always be the same to allow us to hop from any server to another server. Either the keys or entire object can be sent over grpc. 
* Creates an option called `FetchObjectFromKeys` that generates the "__federation" field on an object, and takes in a function as an arg that use used for the shadow function to fetch the object from the keys
* Adds validation that if an object is federated on one server, it is federated on all the other servers with that object
https://paper.dropbox.com/doc/Federation-API-Updated--A4uTEGk52asO9hNzGXB3ZiztAg-f3mzf2dC0zjl60U7ReHAj

Federation API 

---

federation/executor.go
federation/executor_test.go
federation/planner.go
federation/planner_test.go
federation/schema.go
federation/testdata/TestBuildSchemaKitchenSink.snapshots.json
graphql/schemabuilder/function.go
graphql/schemabuilder/schema.go

We use this to identify subqueries and refetch the objects, but due to apollo ts compatibility we need to rename it with a single underscore. The doubel underscore is reserved for introspection queries

Rename "__federation" to "_federation"

---

graphql/schemabuilder/schema.go

This field func often requires db queries or expensive fetching, and should have the expensive tag. This allows it to be called in a seperate goroutine, although it only has to be callled once

federation/schema: FetchObjectFromKeys is expensive

---

federation/executor.go
federation/schema.go
federation/testdata/TestBuildSchemaKitchenSink.snapshots.json
graphql/schemabuilder/schema.go

For apollo ts convention, field funcs need to start with a lowercase letter. We can't force the object name to be lowercase, but we can force the service name, so I switched the ordering.

Federation Name Convention

---

federation/executor.go
federation/schema.go
federation/testdata/TestBuildSchemaKitchenSink.snapshots.json
graphql/schemabuilder/schema.go

Apollo ts requires field func Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/

federation: federated method name has _ instead of -

---

federation/planner.go

For fields on a federated object, it uses the service selector to know which service to run it on, and needs to be able to select a fields. It can have federated keys and have a customer service, so we want to remove the error check

federation/planner: remove check for requiring federated keys

---

graphql/schemabuilder/pagination.go

We want to allow pagination to compare strings after lowercasing them since it makes the sort more intuitive in some cases. There is now a custom sort order called `asc_lower` and `desc_lower` to support this without changing the default sorting.

Lowercase sort of pagination

---

federation/executor_test.go
federation/normalize.go

Fixed a federation bug where for nested fragments we weren't setting the selection set to equal the flattened selections. I also added a test that would catch this scenario

Federation Bug Missing Selections

---

graphql/schemabuilder/batch.go
graphql/schemabuilder/pagination.go
graphql/schemabuilder/types.go

We use to call it ShouldUseFallbackFunc, but if its true we use the batch func and if its false we use the
fallback func. This is a bit misleading, but since its an internlly used structure, we can rename it without
causing any regressions

graphql/schemabuilder: rename to ShouldUseBatchFunc

---

federation/customexecutor_test.go
federation/executor.go
federation/executor_test.go

There's a bug where unmarshaling graphql response strings into
interfaces was turning MaxInt64's into 9223372036854776000 which
overflows int64. We discovered this because we were getting errors
when trying to unmarshal json into a go struct int64 field.
This happens because json.Unmarshal treats numbers as float64s, and
to preserve the int64 value we have to use a json decoder and UseNumber
instead.
See go playground snippet for an example of this behavior:
https://play.golang.org/p/gL8f4BsJ0M-
See stackoverflow for fix:
https://stackoverflow.com/questions/16946306/preserve-int64-values-when-parsing-json-in-go

Federation Unmarshalling Errors

---

graphql/introspection/introspection.go
graphql/introspection/testdata/TestComputeSchemaJSON.snapshots.json

this is a no-op directive that will be used on the client-side by our type generation system
See this PR for a deeper explanation:
https://github.com/samsara-dev/backend/pull/93693
Screenshot if it working in GraphiQL:

graphql inspection: add type_as_optional directive

---

sqlgen/db.go
sqlgen/db_test.go
sqlgen/mysql.go
sqlgen/mysql_test.go
sqlgen/reflect.go
sqlgen/reflect_test.go

The sqlgen API currently only supports upserting a single row at a time. In order to allow for more performant batch upserts, this change adds support for a batch upsert API.

go sqlgen: add an API to batch upsert rows in sqlgen

---

sqlgen/mysql.go
sqlgen/mysql_test.go

This change updates the SimpleWhere ToSQL functionality to allow handling of IS NULL filtering. To match NULL columns, explicitly pass in the column name with nil value into the sqlgen.Filter.

sqlgen: SimpleWhere IS NULL filter support

---

batch/index.go

currently, json.Marshal on batch.Index throws an error `json: unsupported type: map[batch.Index]bool` when attempting to run. This change fixes that issue by implementing MarshalText and UnmarshalText on batch.Index

batch index: implement MarshalText and UnmarshalText

---

federation/normalize.go
federation/normalize_test.go
federation/planner.go

Currently, we are maintaining a list of all fragments that are not
applicable to the current type in flattenFragments. For each
selectionSet, we append the list of unused fragments to the selection
set's fragments. However, we never again use selectionSet.Fragments
again, even in child recursive calls, and do not need it to flatten
the rest of the selectionSet. Thus, it is safe to remove this
logic.
As a result of this logic, there was a bug: if multiple selections use the same
fragment, then we mutate the fragment's selectionSet in child recursive
calls. This results in a fragment.SelectionSet.Fragments array that
grows exponentially in size, and runtime grows exponentially as well as
we process that fragment array. Removing this logic fixes this bug.

go federation: remove unnecessary fragments from flatten

---

sqlgen/integration_test.go
sqlgen/mysql.go
sqlgen/mysql_test.go
sqlgen/reflect.go

Added a ForUpdate option to the SelectOptions, in order to lock rows in a transaction using the SELECT ... FOR UPDATE syntax. The mysql documentation for locking reads can be found here: https://dev.mysql.com/doc/refman/5.6/en/innodb-locking-reads.html

go sqlgen: Add SELECT ... FOR UPDATE support

---

reactive/rerunner.go

In addition to tracking the dependencies for a query, we will also provide tooling for a WorkScheduler to track the dependencies for a single selection.
For example, one could change the implementation of the WorkScheduler [defined here](https://github.com/samsarahq/thunder/blob/master/graphql/batch_scheduler.go) like so:
Before:
```
func (r *immediateGoroutineSchedulerRunner) runEnqueue(resolver UnitResolver, units ...*WorkUnit) {
for _, unit := range units {
r.wg.Add(1)
go func(u *WorkUnit) {
defer r.wg.Done()
units := resolver(u)
r.runEnqueue(resolver, units...)
}(unit)
}
}
```
After:
```
func (r *immediateGoroutineSchedulerRunner) runEnqueue(resolver UnitResolver, units ...*WorkUnit) {
for _, unit := range units {
r.wg.Add(1)
go func(u *WorkUnit) {
defer r.wg.Done()
u.Ctx = …
```

reactive/rerunner: add dependencySetForSelection

---

federation/normalize.go
graphql/types.go
graphql/types_test.go

In mergeSameAlias, we make a shadow copy of each selection and then append
to copy.selectionSet.selections later.
Since append in GO does not always create a new slice, there is chance we
are appending to the original selectionSet.selections slice. This could cause
the recursively flatten function to run into an infinite loop in some cases.
This commit make a new selectionSet for each copy so we will not append to the
original selections later in the function.
This change does not increase the runtime too much. 
```
Current
BenchmarkNormalize2-8   	    5182	    193595 ns/op	  101487 B/op	    2131 allocs/op
New
BenchmarkNormalize2-16    	    5040	    248245 ns/op	  105241 B/op	    2232 allocs/op
```

normalize: fix a bug in mergeSameAlias

---

graphql/batch_executor.go

In order to tag query executions as batched or not, and expensive or not, we expose methods on the work unit that provide this info.

graphql/batch_executor: expose IsExpensive and IsBatch workunit fields

---

graphql/schemabuilder/reflect_test.go
graphql/schemabuilder/schema.go
graphql/schemabuilder/schema_test.go
graphql/schemabuilder/testdata/duplicatetypes.go
graphql/schemabuilder/testpackage/types.go

Introspection assumes that each type in the schema is unique.
Note that package names are not considered when comparing type names.
In other words, foo_package.SomeType and bar_package.SomeType
are considered to have the same name.
This causes issues with the type resolution as only one type
of each name can exist in the schema. For example, one might
define 2 fieldfuncs, one returning foo_package.SomeType and
another returning bar_package.SomeType. The introspection
query will incorrectly declare that both fieldfuncs return
the same type: one of foo_package.SomeType or bar_package.SomeType.
In order to avoid type collisions, we will fail to build the
schema if we detect duplicate types in the GraphQL schema.
We iterate over every object's registered fieldfuncs,
recursing through each …

graphql/schemabuilder/schema: enforce unique type names

---

federation/executor.go
federation/executor_test.go

It is possible for a federation subplan to receive an empty set of keys (this happens when the root plan returns an empty selection and passes it off to a subplan). When this happens, currently the executor assumes the lack of keys means the plan is a root plan, and will try to execute without a federation key, leading to an error if the service does not know about the field.
This commit will explicitly pass in whether or not an execution plan is a root plan or not, and will early return with an empty result if the plan is not a root plan, and the set of federation keys is empty.

go federation: add handling for empty keys for non-root plans

---

federation/executor.go

go append is not thread safe, so we should put it inside the mutex

go executor: move append inside mutex

---

federation/planner.go
graphql/introspection/introspection.go

This commit adds a helper func that will help the planner determine whether or not the selection is part of an introspection query. If so, this field will be routed to be resolved by the introspection client.

go federation: move introspection queries to its own client
