graphql/executor.go, graphql/server.go, livesql/live.go, reactive/rerunner.go, sqlgen/db.go
Add opentracing support on thunder subscriptions for individual field execution, and live/non-live sql query execution.
=> Add opentracing support

.travis.yml
=> infra: add travis ci

example/main.go, graphql/executor.go, graphql/introspection/introspection.go, graphql/introspection/introspection_test.go, graphql/introspection/test-schema.json, graphql/schemabuilder/reflect.go, graphql/types.go
See commit messages.
The reflect.go file is going to need a clean-up sooner rather than later...
=> add basic support for non-nullable types

graphql/await.go, graphql/await_test.go, graphql/end_to_end_test.go, graphql/executor.go, graphql/executor_test.go, graphql/schemabuilder/reflect_test.go, graphql/server.go, internal/json.go, reactive/diff/diff.go, reactive/diff/diff_test.go
Simplifies godoc, if nothing else.
=> graphql: extract diff to its own package reactive/diff

opentracingkit/opentracingkit.go, sqlgen/db.go
=> Add MaybeStartSpanFromContext helper

batch/batch.go, batch/batch_test.go
Adding support for a second timer in the batch function execution logic,
which is reset every time the batch fn is invoked. This is separate from
the MaxDuration timer, which is increased to 10ms as an absolute time
restriction. The interval timer will expire unless the batch fn is
invoked every 500us.
=> graphql batch: Increase waiting period if batch fn is invoked rapidly

reactive/rerunner.go
Updating Rerunner.run() to immediately return if the cancelCtx function
is invoked, since we may have a client that has specified a large
minRerunInterval. For example, if the client specifies minRerunInterval
= math.MaxInt64, then run() will be called once with delay=0, and then a
second time (due to computation.node.handleInvalidate(r.run)) with a
very large delay. The second sleep causes the rerunner object and its
associated cache to stay alive for the lifetime of the process.
The fix for this potential memory leak is to select on both ctx.Done and
the sleep timer, and return immediately if cancelCtx() is called.
=> reactive rerunner: Fix potential rerunner memory leak

merge/merge.go, merge/merge_test.go
Test Plan:
Minimal tests added; more upcoming.
=> merge: Add support for merging update diffs into an existing object.

graphql/server.go
Allow calling code to specify different schemas per query type.
=> graphql: add support for separate mutation schema

diff/diff.go, diff/diff_test.go
=> diff: always use append to start diff indices

README.md
Seems useful to write a note about this, so that the answer for https://twitter.com/qiyh1910/status/967069977277734912 is clearer.
=> readme: add guide for generating schema.json / introspection query

graphql/server.go
This PR adds support for passing additional handlers down to the websocket handler, since thunder directly negotiates the websocket connection. This is useful for passing additional messages over the websocket.
=> graphql: support passing generic handlers to ServeJSONSocket

graphql/server.go
=> generic handlers were a mistake

client/src/index.ts
Export things that are missing for this to be useful.
=> client: export GraphQLData, GraphQLError, GraphQLResult

graphql/introspection/introspection.go, graphql/introspection/introspection_test.go, graphql/introspection/test-schema.json
=> graphql: change introspection to sort enumvals and test it

graphql/schemabuilder/reflect.go
=> graphql/schemabuilder: add godocs for Enum registration function

graphql/schemabuilder/reflect.go, graphql/schemabuilder/reflect_test.go
Full credit to @vavrusa (https://github.com/samsarahq/thunder/pull/120) for these changes. This will help a lot with finishing my custom types PR
=> schemabuilder: allow int8 and unsigned integer types

graphql/end_to_end_test.go, graphql/schemabuilder/pagination.go
change count to totalCount for pagination
=> graphql: change count field in Connection type to TotalCount

graphql/parser.go, graphql/parser_test.go, graphql/types.go
I don't see places where this is used in the package.
=> graphql: remove unused complexity code

sqlgen/integration_test.go, sqlgen/reflect.go
Don't require registration for scalars that support the Scannable interface.
I'll add tests here but wanted to get your opinion on it first
=> sqlgen: support types that satisfy Scannable natively

livesql/example_test.go, livesql/integration_test.go, livesql/live.go, sqlgen/integration_test.go, testfixtures/custom_type.go, testfixtures/db.go
Add an integration on LiveSQL so we know when we're breaking it.
=> go livesql: add integration test

.travis.yml
Let's track what code we're actually testing :+1:
=> add coveralls

graphql/schemabuilder/reflect.go, graphql/schemabuilder/reflect_test.go
@rushilgoel @vavrusa @jellevandenhooff @changpingc @oliversong
=> thunder - float32 field support

CHANGELOG.md, livesql/marshal.go, thunderpb/dependency.pb.go, thunderpb/dependency.proto
To cut down memory usage. 
I will vendor this and make sure inflight snapshot still loads.
=> use oneof for thunderpb.Field

client/src/tests/merge.spec.ts
it's scary that this wasn't tested, but, hey! it passes!
=> client: port merge test from go

CHANGELOG.md, graphql/connection_test.go, graphql/schemabuilder/pagination.go
I refactored this a little bit as part of the process for understanding what's going on. I've added documentation and extracted individual components to keep cognitive load a little lighter when reading this.
Next step: adding filters / sorting
=> Pagination: Refactor

graphql/schemabuilder/pagination.go
Because we might be resolving many, many nodes, applySort and applyFilter need to be parallelized.
=> schemabuilder: Parallelize filter and sort functions

graphql/http.go, graphql/middleware.go, graphql/server.go
To use it in a custom HTTP endpoint.
=> go graphql: expose runMiddlewares

graphql/schemabuilder/input.go
Summary: The type annotation that would be linked with an optional field
would not be "optional" meaning that new fields that would be added
would have issues getting parsed by the frontend.  This change modifies
the graphql schema view to have "optional" fields be truly optional
from graphql's perspective.
=> go schemabuilder: Make Type annotation for "optional" fields optional.

reactive/ctxmutex.go, reactive/ctxmutex_test.go, reactive/rerunner.go
more conservative change than https://github.com/samsarahq/thunder/pull/235
=> go reactive: make reactive.Cache locker acquire take context

graphql/http.go
Did a derp and accidentally closed https://github.com/samsarahq/thunder/pull/242 by merging it into a non-master branch... derp derp derp.
=> go graphql: Add ability to override HTTP graphql executor

sqlgen/db.go, sqlgen/integration_test.go
WithShardLimit lets you point a sqlgen.DB add a shard where all values must
satisfy some constraint (eg. customer ID = x.) The check at the sqlgen.DB
layer enforces all operations actually specify the shard key to catch
confused queries going the wrong place.
=> sqlgen: add WithShardLimit

graphql/batch_executor.go
Add public method for accessing the "selection" attribute of WorkUnit.
=> Expose WorkUnit.Selection

graphql/benchmark_test.go, graphql/schemabuilder/pagination.go
Paginated filters that aren't batched should only spawn go routines per node if every node is doing an expensive operation. If a paginated filter is not doing an expensive operation, the overhead of spawning that many go routines takes more time. The benchmarks below show this.
```
BenchmarkFiltersBatched10Items                     30000             39562 ns/op           15851 B/op        247 allocs/op
BenchmarkFiltersNotBatched10Items                  50000             28960 ns/op           12886 B/op        234 allocs/op
BenchmarkFiltersNotBatched10ItemsExpensive         30000             60457 ns/op           14703 B/op        245 allocs/op
BenchmarkFiltersBatched100Items                    10000            114775 ns/op           69400 B/op        930 allocs/op …
```
=> Non-expensive Filter Execution

graphql/batch_executor_test.go, graphql/end_to_end_test.go, graphql/schemabuilder/batch.go, graphql/schemabuilder/function.go, graphql/schemabuilder/pagination.go, graphql/schemabuilder/reflect_test.go, graphql/schemabuilder/types.go
=> Revert "go graphql/schemabuilder: add Expensive field func option"

graphql/schemabuilder/pagination.go
Parallelizes the processing of batched vs nonbatched vs expensive. The use case is if you have multiple batch filters and multiple nonbatched filters, it shouldn't be waiting for one to finish before starting the other. They should be executed in parallel
I created a field func with 2 batched filters and 2 nonbatched filters to see the impact
Before
```
BenchmarkFilters10Items            30000             67672 ns/op           19236 B/op        300 allocs/op
BenchmarkFilters100Items            5000            277301 ns/op           97238 B/op       1396 allocs/op
BenchmarkFilters1000Items           1000           2410648 ns/op         1026338 B/op      12207 allocs/op
```
After 
```
BenchmarkFilters10Items            30000             52655 ns/op           18434 B/op        291 allocs/op …
```
=> Paginated Filters Optimization

graphql/schemabuilder/pagination.go
Doesn't allocate the arrays twice
```
nodesToKeep := make([]bool, len(nodes))
expensiveNodesToKeep := make([]bool, len(nodes))
batchedNodesToKeep := make([]bool, len(nodes))
```
=> Paginated Filters: Doesn't allocate array twice 

graphql/batch_executor.go
Summary: In order to support advanced features like adding metric tags
per fieldfunc or tracing, we need to expose the context of the work unit.
Unfortunately trying to enumerate the functionality we want for the ctx
(e.g. Value/WithValue) would not work for all cases where we actually need
to pass in a real context to other functions (and they return a new ctx
with the type added).  So this commit just exposes the ctx value.
=> go graphql: Expose the ctx for work units

graphql/schemabuilder/pagination.go, graphql/schemabuilder/types.go
Previously we made a filter struct to pass information, but realized we didn't actually need it. Same functionality, just makes the code easier to read.
=> Refactoring Paginated Filters

graphql/schemabuilder/types.go
Added the ability to pass in options to sort methods. This will be used to pass in the expensive flag.
=> Options for paginated sort methods

reactive/rerunner.go
Summary: Some pieces of code will hold onto the context waiting for it
to be done (usually in a goroutine).  This means that all the objects
that are stored on the context are held until the original context is
marked as "done".  This would not happen until the websocket/http
request finishes.  So for continous requests we have a leak where each
intermediary context is holding onto the entire cache stack (and
anything else on the context) until we reset the websocket connection.
This commit adds a cancel to context for each reactive.Run.  This should
allow all code that depends on the context.Done() to be able to clear/reset
between runs.
=> go reactive: Cancel context after each reactive Run

graphql/batch_executor_test.go, graphql/end_to_end_test.go, graphql/schemabuilder/batch.go, graphql/schemabuilder/function.go, graphql/schemabuilder/pagination.go, graphql/schemabuilder/reflect_test.go, graphql/schemabuilder/types.go
Already reviewed in #281, but worth another review to make sure it works correctly with the recent pagination improvements.
=> Expensive field func option take two

sqlgen/db.go
We are changing txkey to be a sql.DB instead of a sqlgen.DB
so that if two sqlgen DBs are mapped to the same
sql DB, they can share one tx.
=> db: Change txkey to take in a sql.DB instead of sqlgen DB

graphql/schemabuilder/build.go, graphql/schemabuilder/output.go, graphql/schemabuilder/reflect_test.go, graphql/schemabuilder/schema.go, graphql/schemabuilder/testpackage/types.go
=> Revert "graphql: prevent type names from being duplicates" 

graphql/batch_executor.go
Adds the nonExpensive flag to the context. This can be used to prevent nonexpensive execution if the field func later makes a db/grpc request.
=> Added the NonExpensive value to the context

graphql/batch_executor.go
Checks whether it is a query of mutation before adding the expensive tag. This is useful since we don't want to stop nonexpensive mutations from making db/grpc requests.
=> NonExpensive context tag for only querries

graphql/batch_executor.go
Object name now gets passed down. Also "nonexpensive" doesn't get added to contexts that are queries
=> Passing ObjectName correctly to subworkunits

graphql/schemabuilder/pagination.go
Batch filter/sort fields now give more correct error messages.
=> Thunder pagination error messages

livesql/binlog.go
This sets the hostname of the slave hosts to be "localhost". If unset,
as it was, it will use the os.Hostname() value as the hostname instead.
In rare situations, the OS's hostname could be too long for the slave
host's "host" field, and we got an error like:
```
panic: ERROR 1105 (HY000): Failed to register slave: too long 'report-host'
```
which would put the server into a crash loop.
Before this change:
```
mysql> show slave hosts;
+------------+--------------------------+------+-----------+------------+
| Server_id  | Host                     | Port | Master_id | Slave_UUID |
+------------+--------------------------+------+-----------+------------+
| 2926146535 | Arthur-Huang-MacBook-Pro | 3308 |         1 |            |
| 4101280766 | Arthur-Huang-MacBook-Pro | 3308 |         1 | …
```
=> go livesql/binlog: limit slave host name length in binlogSyncerConfig

graphql/writer.go
Summary: OutputNodes keep a reference to their "parent" so we can do
path matching going back through the stack.  Unfortunately this creates
a circular reference (node->parent->res(child)->node) which can make it
hard for go's garbage collector from clearing memory quickly (especially
if the outputNode graph gets very large).
This commit stops tracking the whole parent node, and only tracks the
parent node's new pathTracker variable.
Test Plan: We were actually loading too much data and causing OOMs on 
our devices because we couldn't keep up with GC.  I wrote this as a test and
suddenly the GC could keep up.  (I've also pulled this branch locally and
seen the same results).
=> go graphql/writer: Remove circular reference from outputNodes

graphql/introspection/introspection.go, graphql/introspection/testdata/TestComputeSchemaJSON.snapshots.json
Per https://graphql.org/learn/introspection/.
Fixes #347.
Based on #348.
=> graphql: introspection empty type name should be nil

graphql/batch_executor.go, graphql/directive.go, graphql/directive_test.go, graphql/introspection/introspection.go, graphql/introspection/testdata/TestComputeSchemaJSON.snapshots.json, graphql/parser.go, graphql/parser_test.go, graphql/testdata/TestDirectivesWithFragments.snapshots.json, graphql/testdata/TestIncludeDirectives.snapshots.json, graphql/testdata/TestSkipDirectives.snapshots.json, graphql/types.go
Directive support for skip and include as following https://graphql.org/learn/queries/#directives
=> Directive support for skip and include

federation/executor.go, federation/executor_test.go
Federated executor where we have a union type in which we need to parse the keys and send a subquery to a different gql server
=> Federation Executor: nested services union types

graphql/schemabuilder/input.go, graphql/schemabuilder/reflect_test.go
=> support int and uint as input args type

sqlgen/db.go
A previously undhandled case where a query can hit constants lookups
that mysql resolves to an impossible where. These queries should be
allowed since they're performant regardless of indexes.
For samsara reviewers, see this PR as proof that this is functional. Without the thunder change the explain parsing was error'ing :( https://github.com/samsara-dev/backend/pull/74019
=> go sqlgen/db.go: add explain support for impossible where

federation/normalize.go
We had an issue where when we turned on federation when it was planning the query we saw high spikes on memory on the function where it merges queries with the same alias. The query was always successfully removing all the repeats, but the bug was making it run through those lines more often then it needs to 
In this example, this is the input
```
{
users {
... userFragment1
... userFragment2
}
}
fragment userFragment1 {
name
}
fragment userFragment2 {
name
phoneNumber
... userFragment3
}
fragment userFragment3 {
name
phoneNumber
}
```
and this is the expected output. 
```
{
users {
name
phone number
}
}
```
When we flatten all the fragments, we check if they are all on the User type, and if they are we added it to the list of selections. At this point, its safe to remove it as a fragment …
=> Removing Repeated Selections and Fragments

federation/executor_test.go
This commit adds paginated field funcs to our current federation endpoint tests to make sure that even with multiple hops (fields across different schemas), the result from the query still is correct
=> go federation: add pagination tests

graphql/connection_test.go, graphql/schemabuilder/pagination.go
Allow users to provide filter and sort fields that implement the connection arguments of the FieldFunc.
This allows for pre-filtering on sort fields in the event that a sort field has to be filtered before providing sort values.  It also provides more flexibility in the filter fields and what type of action they can take if the arguments are passed directly to them.
Passing the ConnectionArgs.Args as userArgs to the GraphQL resolvers through the applySort and applyTextFilterField methods exposing the userArgs down to the subsequent schemabuilder methods (FilterField, BatchFilterField, SortField, BatchSortField)
This allows us to take action on these userArgs at the filter/sort level such as within a sort method, filtering on some userArgs before actually populating sort values. For …
=> Pass args down to sort and filter methods
